export enum ErrorCode {
	DATA_NOT_FOUND = 'DATA_NOT_FOUND',
	DATA_INACTIVE = 'DATA_INACTIVE',
	INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
	INCORRECT_CREDENTIALS = 'INCORRECT_CREDENTIALS',
	PERMISSION_DENIED = 'PERMISSION_DENIED',
	RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
	VALIDATION_ERROR = 'VALIDATION_ERROR',
	CONFLICT = 'CONFLICT',
	INTERNAL_ERROR = 'INTERNAL_ERROR',
	BAD_REQUEST = 'BAD_REQUEST',
}
